### ISSUE TITLE
Exceptions repeating in latest new release - not working (EntityRegistry can't be used in 'await' expression)

### ISSUE THREAD

**Issue by KruseLuds** [zachcheatham/ha-omada#43] opened 2022-08-17 23:12 UTC
This is from the syslog, 

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: #033[31m2022-08-17 18:22:31.833 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: Traceback (most recent call last):

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:     await self.remove()

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: TypeError: object EntityRegistry can't be used in 'await' expression

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: #033[0m

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: #033[31m2022-08-17 18:22:31.863 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: Traceback (most recent call last):

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:     await self.remove()

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: TypeError: object EntityRegistry can't be used in 'await' expression

Aug 17 18:22:31 kruse-pi 924cc5103eb5[874]: #033[0m

**Comment by zachcheatham** [comment] 2022-08-18 16:01
Which version of Home Assistant?

**Comment by KruseLuds** [comment] 2022-08-19 16:38
Here is the version information and more informationm from the log today:

19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.325 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.337 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.346 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.350 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.355 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.359 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.368 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.370 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.371 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.375 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.381 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.385 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.395 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.399 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[0m
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: #033[31m2022-08-19 12:03:23.403 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-6fdc5898c2e1160fc84843132266b6f4': ()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: Traceback (most recent call last):
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 187, in async_update
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     await self.remove()
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:   File "/config/custom_components/omada/device_tracker.py", line 176, in remove
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]:     entity_registry = await self.hass.helpers.entity_registry.async_get(self.hass)
Aug 19 12:03:23 kruse-pi 155295bf09aa[891]: TypeError: object EntityRegistry can't be used in 'await' expression


![image](https://user-images.githubusercontent.com/96640689/185666253-57c1df0c-07b9-4f40-a90d-e2025e8ffc48.png)

**Comment by KruseLuds** [comment] 2022-08-21 17:37
Any update?

**Comment by zachcheatham** [comment] 2022-08-26 04:00
Duplicate of #42

**Closed by zachcheatham** 2022-08-26 04:00 UTC
