### ISSUE TITLE
Errors Loading

### ISSUE THREAD

**Issue by KruseLuds** [zachcheatham/ha-omada#34] opened 2022-06-25 11:13 UTC
Note the below from my HA log. I shouldn't have to go reload it every day after my router or HA is restarted:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/omada/controller.py:147
Integration: TP-Link Omada (documentation)
First occurred: 6:53:21 AM (1 occurrences)
Last logged: 6:53:21 AM

Error setting up entry Master_Controller: Ridgewood Estate for omada
Traceback (most recent call last):
  File "/config/custom_components/omada/controller.py", line 147, in get_api_controller
    await controller.login()
  File "/config/custom_components/omada/api/controller.py", line 48, in login
    await self._update_api_info()
  File "/config/custom_components/omada/api/controller.py", line 65, in _update_api_info
    response = await self._request("get", f"{self.url}/api/info")
  File "/config/custom_components/omada/api/controller.py", line 180, in _request
    async with self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1120, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/omada/__init__.py", line 32, in async_setup_entry
    await omada_controller.async_setup()
  File "/config/custom_components/omada/controller.py", line 74, in async_setup
    self.api = await get_api_controller(
  File "/config/custom_components/omada/controller.py", line 147, in get_api_controller
    await controller.login()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by otiswrx** [comment] 2022-08-24 01:28
I also just started receiving this error, and the integration no longer loads. Only change is updating HA OS this afternoon. (HA OS =version 8.5)

**Comment by zachcheatham** [comment] 2022-11-01 18:52
This is a duplicate of #33

**Closed** 2022-11-01 18:52 UTC
