### ISSUE TITLE
Devices no longer work in 0.31, due to async_get_registry change

### ISSUE THREAD

**Issue by ping-localhost** [zachcheatham/ha-omada#44] opened 2022-08-24 12:39 UTC
Since 0.31 my devices no longer show up in Home Assistant. I've downgraded to 0.30 and everything instantly works again. 

---

Changing `async_get_registry` to `async_get(hass)` seems to have broken something 😅

**Comment by zachcheatham** [comment] 2022-08-25 14:37
Duplicate of #42

**Closed by zachcheatham** 2022-08-25 14:37 UTC
Labels: bug
