### ISSUE TITLE
If I restart HA, ha-omada fails.

### ISSUE THREAD

**Issue by moridew** [zachcheatham/ha-omada#48] opened 2022-10-24 08:43 UTC
Hello.

If I restart HA, ha-omada fails.

normal running at Reload on 'Settings - Device & Services - TP-Link Omada' 

Problems occur only occasionally when HA is restarted, can it be improved?

Thank you.

**Comment by zachcheatham** [comment] 2022-11-01 18:48
Is this possibly a duplicate of #33?

**Comment by moridew** [comment] 2022-11-04 04:48
I think it's similar. 
And I think it's solved in 0.3.3. If I wait a little while after restarting, it loads normally.

Thank you!

**Closed** 2022-11-04 04:49 UTC
